server:
  port: ${PORT:8086}

spring:
  application:
    name: ${APP_NAME:solutions}

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}?ssl=${DB_SSL_ENABLED:false}&sslmode=${DB_SSL_MODE:require}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:rabbitmq}
    password: ${RABBITMQ_PASS:rabbitmq}
    virtual-host: ${RABBITMQ_VHOST:/}
    ssl:
      enabled: ${RABBITMQ_SSL_ENABLED:false}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-retries: 3

app:
  jwt:
    secret: ${JWT_SECRET:8x/c+pXQ3Q9m+9b2tZ/vT1gQzYqXlO/m+HwA9R5z7J8=}
  challenges:
    base-url: ${CHALLENGES_BASE_URL:http://localhost:8081}
    internal-token: ${CHALLENGES_INTERNAL_TOKEN:changeme-internal-token}
  messaging:
    challenges:
      exchange: ${CHALLENGES_EXCHANGE:challenges.solutions.exchange}
    code-execution:
      exchange: ${CODE_EXECUTION_EXCHANGE:codeexecution.exchange}
    solutions:
      queues:
        solution-requested: ${SOLUTIONS_QUEUE_SOLUTION_REQUESTED:solutions.solution.requested.queue}
        execution-started: ${SOLUTIONS_QUEUE_EXECUTION_STARTED:solutions.execution.started.queue}
        execution-completed: ${SOLUTIONS_QUEUE_EXECUTION_COMPLETED:solutions.execution.completed.queue}
      routing-keys:
        solution-requested: ${SOLUTIONS_ROUTING_KEY_SOLUTION_REQUESTED:challenges.solution.requested}
        execution-requested: ${SOLUTIONS_ROUTING_KEY_EXECUTION_REQUESTED:challenges.solution.execution.requested}
        execution-started: ${SOLUTIONS_ROUTING_KEY_EXECUTION_STARTED:codeexecution.solution.execution.started}
        execution-completed: ${SOLUTIONS_ROUTING_KEY_EXECUTION_COMPLETED:codeexecution.solution.execution.completed}
  solutions:
    default-max-attempts: ${SOLUTIONS_DEFAULT_MAX_ATTEMPTS:10}
    attempt-reset-window-minutes: ${SOLUTIONS_ATTEMPT_RESET_WINDOW_MINUTES:60}

# Eureka Config
eureka:
  instance:
    # When using Docker/k8s then true
    prefer-ip-address: ${EUREKA_PREFER_IP:true}
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /api/v1/${spring.application.name}/actuator
  endpoint:
    health:
      show-details: never
